name: Hello, World!
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:

      - name: echo head_ref
      - run: echo '${{ github.head_ref }}'

      - name: echo ref
      - run: echo '${{ github.ref }}'