name: typescript

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - name: get result URL
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run: echo ::set-env name=RESULT_URL::hoge
      - name: slack test
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: "good"
          SLACK_MESSAGE: ${{env.RESULT_URL}}
          SLACK_TITLE: "slackのメッセージのテスト"
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
